# Generated by Django 4.0.4 on 2022-04-28 07:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Gender', models.IntegerField(null=True)),
                ('RFID', models.CharField(max_length=15, null=True)),
                ('RoleID', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('people', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.people')),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 4, 28, 14, 23, 43, 672571))),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.people')),
            ],
        ),
    ]
