# Generated by Django 4.0.4 on 2022-04-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('ID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Age', models.IntegerField(null=True)),
                ('Gender', models.IntegerField(null=True)),
                ('RFID', models.CharField(max_length=15, null=True)),
                ('RoleID', models.IntegerField(null=True)),
            ],
        ),
    ]
