# Generated by Django 4.0.4 on 2022-04-28 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 14, 23, 54, 988017)),
        ),
    ]
