# Generated by Django 4.0.4 on 2022-04-28 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_timerecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 14, 28, 14, 180587)),
        ),
    ]
