# Generated by Django 4.0.4 on 2022-05-11 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_timerecord_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='checkFace',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='checkRFID',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 8, 20, 2, 533452)),
        ),
    ]
