# Generated by Django 3.2.13 on 2022-05-05 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_timerecord_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='ID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 13, 24, 24, 85446)),
        ),
    ]
