# Generated by Django 4.0.4 on 2022-05-11 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_timerecord_checkface_timerecord_checkrfid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='ok',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 11, 8, 22, 53, 733815)),
        ),
    ]
