# Generated by Django 3.2.13 on 2022-05-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220505_1324'),
        ('home', '0005_timerecord_ok_alter_timerecord_time'),
    ]

    operations = [
    ]
