# Generated by Django 4.0.2 on 2022-05-19 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20220512_1258'),
        ('home', '0006_rename_checkface_timerecord_checkpeople_and_more'),
    ]

    operations = [
    ]
