# Generated by Django 4.0.2 on 2022-05-19 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_merge_20220519_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpeople', models.IntegerField(default=0, null=True)),
                ('ok', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='timerecord',
            name='ok',
        ),
        migrations.AlterField(
            model_name='people',
            name='ID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 12, 5, 22, 885602)),
        ),
    ]
