# Generated by Django 4.0.2 on 2022-05-19 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_checkpeople_remove_timerecord_ok_alter_people_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpeople',
            name='id_check',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 12, 6, 39, 763631)),
        ),
    ]
