# Generated by Django 4.0.2 on 2022-05-19 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_checkpeople_id_check_alter_timerecord_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpeople',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 12, 14, 32, 423927)),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 12, 14, 32, 423041)),
        ),
    ]
