# Generated by Django 4.0.4 on 2022-06-08 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_checkpeople_time_delete_timerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpeople',
            name='image',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='image',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='checkpeople',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 16, 30, 10, 162146)),
        ),
    ]
