# Generated by Django 4.0.4 on 2022-06-08 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_checkpeople_image_people_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpeople',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 16, 42, 8, 457460)),
        ),
    ]
