# Generated by Django 4.0.4 on 2022-06-10 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_checkpeople_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpeople',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='checkpeople',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 16, 55, 2, 239297)),
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
